config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'users#new'

  resources :users do
  	collection do
  		get 'login' => 'users#try_login'
  		post 'login' => 'users#login'
  		get 'log_out'
  	end
  end

  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true

	belongs_to :user
	has_many :article_contents


	def get_content
	 	content = ArticleContent.find_by_id(self.content_id).content
	 	content
	 end 
end

app/models/article_content.rb
class ArticleContent < ApplicationRecord
	belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
	validates :login, presence: { message: "用户名不能为空" }
	# format: { with: /(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z]).*$/, message: "用户名必须包含大小写字母和数字" }
	validates :email, presence: { message: "邮箱不能为空" }
	validates :password, presence: { message: "密码不能为空" }

	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include UsersHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	# before_action :insure_logged_in

	def index
		@articles = current_user.articles
	end

	def new
		@article = Article.new
	end

	def create
		redirect_to new_article_path and return if params[:content].blank?
		@article = Article.new(params.require(:article).permit(:title, :user_id))
		if @article.save
			ac = ArticleContent.new
			ac.content = params[:content]
			ac.article_id = @article.id
			ac.save
			@article.update_attributes(content_id: ac.id)
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def edit
		@article = Article.find_by_id(params[:id])
	end

	def update
		@article = Article.find_by_id(params[:id])
		content_id = @article.content_id
		@ac = ArticleContent.find_by_id(@article.content_id)
		if @ac.content != params[:content]
			ac = ArticleContent.new
			ac.content = params[:content]
			ac.article_id = @article.id
			ac.save
			@article.update_attributes(content_id: ac.id)
		end
		@article.update_attributes(title: params[:article][:title])
		@article.update_attributes(content_id: params[:article][:content_id]) if params[:article][:content_id].to_i != content_id
		redirect_to articles_path
	end

	def show
		@article = Article.find_by_id(params[:id])
	end

	def destroy
		##
	end


	private

	def insure_logged_in
		unless current_user
			redirect_to log_in_users_path
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		
	end

	def new
		@user = User.new
	end

	def create
		params[:user][:password] = Digest::SHA1.hexdigest(params[:user][:password]) if !params[:user][:password].blank?
		@user = User.new(user_params)
		if @user.save
			redirect_to login_users_path
		else
			render 'new'
		end
	end

	def show
		@user = User.find_by_id(params[:id])
	end

	def try_login
	end

	def login
		@user = User.find_by_login(params[:login]) || User.find_by_email(params[:login])
		if @user && @user.password == Digest::SHA1.hexdigest(params[:password])
			flash[:danger] = "请勿重复登录" and redirect_to users_path and return if logged_in?
			log_in @user
			redirect_to users_path
		else
		    flash[:danger] = "用户名或者密码错误，请确认后重试"
		    render 'try_login'
		end
	end

	def log_out
		logout if logged_in?
		redirect_to new_user_path
	end

	def destroy
		
	end

	private

	def user_params
		params.require(:user).permit(:email, :login, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def logged_in?
		!current_user.nil?
	end

	def log_in(user)
		session[:user_id] = user.id
	end

	def logout
		session.delete(:user_id)
		@current_user = nil
	end

	def current_user
		@current_user ||= User.find_by_id(session[:user_id])
	end
end

app/views/articles/edit.html.erb
<%= form_for @article do |f| %>
  <div class="form-group">
    <%= f.label "标题" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "历史内容" %>
    <%= f.select :content_id, @article.article_contents.collect{|s|[s.id, s.id]}, { include_blank: true }, class: "form-control" %>
  </div>
 <div class="form-group">
    <%= label_tag "内容" %>
    <%= text_area_tag :content, @article.get_content, class: "form-control" %>
  </div>
  <div class="form-group text-center">
    <%= f.submit "保存", class: "save_btn btn btn-success col-lg-12" %>
  </div>
<% end %>

app/views/articles/index.html.erb
<table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>标题</th>
          <th>内容</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |article| %>
        <tr>
          <th><%= article.id %></th>
          <td><%= article.title %></td>
          <td><%= article.get_content %></td>
          <td><%= link_to "编辑", edit_article_path(article) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

app/views/articles/new.html.erb
<%#= current_user.inspect %>

<%= form_for @article do |f| %>
<input class="form-control" type="hidden" name="article[user_id]" value=<%= current_user.id %> id="article_user_id">
  <div class="form-group">
    <%= f.label "标题" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

 <div class="form-group">
    <%= label_tag "内容" %>
    <%= text_area_tag :content, nil, class: "form-control" %>
  </div>
  <div class="form-group text-center">
    <%= f.submit "保存", class: "save_btn btn btn-success col-lg-12" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% if current_user %>
hello_<%= current_user.login %>
<br>
<%= link_to "新建文章", new_article_path %>
<%= link_to "退出", log_out_users_path %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<% if @user.errors.any? %>
  <% @user.errors.messages.values.flatten.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
<% end %>
  <div class="form-group">
    <%= f.label "用户名" %>&nbsp;<span style="font-weight: bold; color:red;">*</span>
    <%= f.text_field :login, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "邮箱" %>&nbsp;<span style="font-weight: bold; color:red;">*</span>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label "密码" %>&nbsp;<span style="font-weight: bold; color:red;">*</span>
    <%= f.password_field :password, class: "form-control" %>
  </div>
 <div class="form-group text-center">
   <%= f.submit "保存", class: "save_btn btn btn-success col-lg-12" %>
 </div>
<% end %>

app/views/users/try_login.html.erb
<%= form_tag('/users/login') %>
  <div class="form-group">
    <label for="user_账户">账户</label>
    <%= text_field_tag :login, nil, class: "form-control", placeholder: "用户名或邮箱" %>
  </div>
  <div class="form-group">
    <label for="user_密码">密码</label>
    <%= password_field_tag :password, nil, class: "form-control" %>
  </div>
 <div class="form-group text-center">
   <%= submit_tag "登录", class: "save_btn btn btn-success col-lg-12" %>
 </div>